spring.application.name=test-service
server.port=8085

spring.datasource.url = jdbc:postgresql://localhost:5432/test_db
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.com.iset.spring_integration=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG