/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#283044",
        "on-secondary-container": "#57657b",
        "on-error": "#ffffff",
        "tertiary-container": "#a44100",
        "secondary": "#515f74",
        "inverse-on-surface": "#eef0ff",
        "surface-variant": "#dae2fd",
        "error": "#ba1a1a",
        "surface": "#f8fafc",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "primary": "#3525cd",
        "on-surface": "#131b2e",
        "primary-fixed-dim": "#c3c0ff",
        "secondary-fixed-dim": "#b9c7e0",
        "surface-container": "#eaedff",
        "on-surface-variant": "#464555",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f3ff",
        "surface-container-high": "#e2e7ff",
        "on-tertiary-fixed": "#351000",
        "outline": "#777587",
        "tertiary": "#7e3000",
        "on-tertiary-container": "#ffd2be",
        "on-secondary": "#ffffff",
        "primary-container": "#4f46e5",
        "secondary-fixed": "#d5e3fd",
        "secondary-container": "#d5e3fd",
        "surface-tint": "#4d44e3",
        "inverse-primary": "#c3c0ff",
        "background": "#faf8ff",
        "on-primary-container": "#dad7ff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#e2dfff",
        "on-primary-fixed-variant": "#3323cc",
        "surface-dim": "#d2d9f4",
        "on-secondary-fixed": "#0d1c2f",
        "on-error-container": "#93000a",
        "on-background": "#131b2e",
        "outline-variant": "#c7c4d8",
        "tertiary-fixed": "#ffdbcc",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-fixed-variant": "#7b2f00",
        "tertiary-fixed-dim": "#ffb695",
        "on-primary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "on-secondary-fixed-variant": "#3a485c"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}